artifact_location: file:C:/Users/isazo/OneDrive/Рабочий стол/courses/partfolio/pet_projects/traffic-sign-detection/notebooks/../models/mlflow/451088346565699434
creation_time: 1777103827104
experiment_id: '451088346565699434'
last_update_time: 1777103827104
lifecycle_stage: active
name: /Shared/Ultralytics
