artifact_location: file:C:/Users/isazo/OneDrive/Рабочий стол/courses/partfolio/pet_projects/traffic-sign-detection/notebooks/../models/mlflow/894549507430796363
creation_time: 1777008033817
experiment_id: '894549507430796363'
last_update_time: 1777008033817
lifecycle_stage: active
name: /Shared/Ultralytics
