artifact_location: file:C:/Users/isazo/OneDrive/Рабочий стол/courses/partfolio/pet_projects/traffic-sign-detection/notebooks/../models/mlflow/0
creation_time: 1777103827057
experiment_id: '0'
last_update_time: 1777103827057
lifecycle_stage: active
name: Default
